############################################
# pipeline for predicting stock price with news
# set true to run the pipeline, false to skip the pipeline
[pipeline]
# finance
fin_ingestion = false
fin_processing = true
fin_model = false
# news
news_ingestion = false
news_processing = false
news_model = false
# prediction
predict_model = false
predict_evaluation = false




############################################
[info]
# local path to store all data (change to your local path)
local_data_path = "/Users/xwpeng/Projects/Erdos_NewsFin/data"

# directories names for data files in the Google Drive
# data_raw: raw stock and news data
# data_clean: cleaned and processed stock and news data, which can be used for modeling directly
# model_fin: finance model files and the outputs
# model_news: news model files and the outputs
# model_pre_train: preditive model files and the outputs
# model_pre_eval: evaluation results for the predictive models
dirs_names = ["logs", "config_archive", "data_raw", "data_clean", "model_fin", "model_news", "model_pre_train", "model_pre_eval"]

# training period
train_start_date = "2016-01-01"
train_end_date = "2019-12-31"

# testing period
test_start_date = "2020-01-01"
test_end_date = "2020-12-31"

# should we do cross-validation on the training data?
# note: cv for time series data is based on rolling windows, not random splits
#       so it should fit finance model, news model, and predictive model simultaneously
cross_validation = false




############################################
# parameters for each step in the pipeline
[fin_ingestion]
[fin_ingestion.input]
stock_symbol_file = "stock_symbols.csv"
start_date = "2016-01-01"
end_date = "2020-12-31"
[fin_ingestion.output]
stock_data_file = "stock_data.csv"

[fin_preprocessing]
[fin_preprocessing.input]
stock_data_file = "stock_data.csv"
[fin_preprocessing.output]
stock_data_cleaned_file = "stock_return.csv"

[fin_model]


[news_ingestion]


[news_preprocessing]


[news_model]


[predict_model]


[predict_evaluation]



############################################
# automatically generate when run the predic_stock_w_news.py
# for virsion control of files
[date]